Implement login loader
ChronoBank/Labor-X pull request #123
Opened 2018-07-08 18:07 UTC by alanhanaev

2018-07-08 18:31 UTC, sargonpiraev requested changes

2018-07-08 18:31 UTC, sargonpiraev commented on .eslintignore
> +!src/components/Login/LoginForm/LoginForn.js
fix Forn

2018-07-08 18:31 UTC, sargonpiraev commented on src/api/backend/index.js
> -  const data = JSON.stringify(deepSortByKey({ url: '/api/v1/security/signin/signature/laborx', body }))
do not remove /laborx

2018-07-08 18:31 UTC, sargonpiraev commented on src/api/backend/index.js
> -  return http.post('/security/signin/signature/laborx', body, {
return /laborx

2018-07-08 18:31 UTC, sargonpiraev commented on src/components/Login/LoginForm/LoginForm.js
> +          <div className={css.spinner} />
use material ui https://material-ui.com/demos/progress/ for spinner

2018-07-08 18:31 UTC, sargonpiraev commented on src/components/Login/LoginForm/LoginForm.scss
> +}
rm 
use https://material-ui.com/demos/progress/ instead

2018-07-08 18:31 UTC, sargonpiraev commented on src/components/Login/LoginForm/LoginForm.scss
> +}
del
use https://material-ui.com/demos/progress/ instead

2018-07-09 06:14 UTC, alanhanaev reviewed
Requested changes

2018-07-09 08:02 UTC, sargonpiraev approved these changes

2018-07-09 08:02 UTC, merged