WIP LABX-118
ChronoBank/Labor-X pull request #125
Opened 2018-07-09 02:15 UTC by valyakin

2018-07-12 07:26 UTC, sargonpiraev requested changes

2018-07-12 07:26 UTC, sargonpiraev commented on src/components/Login/LoginOptions/LoginOptions.js
> +    window.onpopstate = this.onBackButtonEvent
if event binded then event must be unbinded too
for example in componentWillUnmount
because it can cause errors and memory leaks

2018-07-12 07:26 UTC, sargonpiraev commented on src/components/Account/AccountPasswordForm/AccountPasswordForm.scss
> +  }
just use https://material-ui.com/demos/selection-controls/#checkboxes

2018-07-12 07:26 UTC, sargonpiraev commented on static/images/svg/checkbox-blue.svg
> +</svg>
use https://material-ui.com/demos/selection-controls/#checkboxes

2018-07-12 11:36 UTC, valyakin commented on src/components/Account/AccountPasswordForm/AccountPasswordForm.scss
> +  }
Will do. was not possible before LABX-300 because of wrong redux-form version for old material-ui

2018-07-16 07:14 UTC, sargonpiraev approved these changes

2018-07-16 07:14 UTC, merged