LABX-115 router on server side
ChronoBank/Labor-X pull request #127
Opened 2018-07-09 13:02 UTC by valyakin

Do not use router on server for links decoration

2018-07-09 14:59 UTC, sargonpiraev requested changes
same error occurs

2018-07-10 08:14 UTC, sargonpiraev requested changes

2018-07-10 08:14 UTC, sargonpiraev commented on src/components/Login/LoginOptions/LoginOptions.js
> +    hideAccount404Dialog: PropTypes.bool,
hideAccount404Dialog is a function

2018-07-10 09:07 UTC, valyakin commented on src/components/Login/LoginOptions/LoginOptions.js
> +    hideAccount404Dialog: PropTypes.bool,
sorry, wrong prop

2018-07-10 11:23 UTC, sargonpiraev approved these changes

2018-07-10 11:24 UTC, merged